name: PackSquash on Tag

on:
  push:
    tags:
      - "**"

jobs:
  packsquash:
    name: Optimize ${{ matrix.pack }}
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        pack:
          [
            vanilla,
            cartoon,
            chinese-mythology,
            city,
            fallout,
            fantasy,
            festive,
            greek-mythology,
            halloween,
            natural,
            plastic,
            steampunk,
          ]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          artifact_name: packsquash-${{ matrix.pack }}
          packsquash_version: v0.4.1
          options: |
            pack_directory = 'Packs/${{ matrix.pack }}'
            output_file_path = '/tmp/${{ matrix.pack }}.zip'
            allow_mods = ['OptiFine']
            zip_spec_conformance_level = 'high'
            never_store_squash_times = true

      - name: Release Packs
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "/tmp/${{ matrix.pack }}.zip"
